language: generic
branches:
  only:
  - master
  - "/^v.*$/"
jobs:
  include:
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew upgrade python@2
    - pip2 install virtualenv
    - python2 -m virtualenv env
    - source env/bin/activate
    - pip2 install numpy
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew unlink python@2
    - brew upgrade python
    - python3 -m venv env
    - source env/bin/activate
    - pip install numpy
  - services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    install: bash .manylinux.sh
    script: true
  - services: docker
    env:
    - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    - PRE_CMD=linux32
    install: bash .manylinux.sh
    script: true
install:
- pip install --upgrade pip wheel
- pip install .[test]
- python setup.py bdist_wheel
script:
- python setup.py test
deploy:
  provider: releases
  api_key:
    secure: XGxrdBhfWHIhrGTWE0R06YbBlURgXOZJMIgh0/ouDduxy5He8zZVcZ0De0PoK0BNlrPtumAyYMwEsSz74sfAy2UVj0Cyq2zd2Ame7srcorOvL79hPKUFvAXj+YMFgjDuSI+4do6v6yHORIkpO1ighbg5jcnCKHcfLrxcpLkbOn7hHiVtSS2iOA5YAQxvl5pmrXCyqm1c6koYY1Le/0Qybv72KBbVHaaaBJX8G4+UTxtby9w7ARyFqFDR4xckp6EAXlodtV1tKrS74GvpyXPBEExYZj+iReuwiGMUBCJnyHIWB9iwwOViYNv+oZOM20heCkAdFDgFM9XT6smk2AIc0pt8RElySk6jQ5yEjkf+WzbP/f+HaloJyoEx2VKAbvZdX3z7R1uOcOB06fUrW/G6iTNZC5kisrTH2BGibOs3sojHkICkfppxOPXoXGsjQACmlfd7e9OmM/AY5uBmx55/TY1xvcl19F38260BRZMBEhk2pE4r0sA840CDFT6jrc90rolQ8871jrQTBS4vMQxqA62g+xNW4bNHuu86y/rrmnQSPgETQke3L3gkmKXYmkW+WEm/HbLLCdGHktgBEaTRv5wYjHmSpQcLyIm9dVR0O5gMuYGYhkutBoiL4WdBUGG3nBxDTW65jcZlxZEbFWsOhhDVnZg5HKdNfOWyvS0Kh+8=
  file_glob: true
  file: dist/cmappertools*.whl
  on:
    repo: dmuellner/cmappertools
    tags: true
  skip_cleanup: 'true'
